name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    # don't cancel 3.12/3.13 just because 3.11 fails
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Show environment (quick sanity)
        run: |
          pwd
          python --version
          ls -la
          echo "--- tests directory ---"
          ls -la tests || true
          echo "--- repo tree (top 2 levels) ---"
          find . -maxdepth 2 -type d -print

      - name: Install deps
        run: |
          python -m pip install -U pip
          # install pytest explicitly in case it's not pinned in requirements.txt
          pip install -r requirements.txt pytest

      # Quick collection to fail early if pytest can't see tests
      - name: Pytest collect-only (debug)
        run: pytest -q --collect-only

      - name: Run full test suite
        run: pytest -v

      # Golden metrics (runs even if above failed on some versions thanks to fail-fast: false)
      - name: Empirical golden metrics
        run: pytest -v tests/test_golden_metrics.py -m empirical
